local rendercam = require "rendercam.rendercam"

function init(self)
	msg.post(".", "acquire_input_focus")
	--msg.post("#level-proxy", "load")
	msg.post("#gamepad-select-proxy", "load")

	rendercam.set_ortho_scale(2)
end
function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		-- Proxy is loaded. Init and enable it.
		msg.post(sender, "init")
		msg.post(sender, "enable")
	end
end